name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      #with:
        # Directory to install Qt
        #dir: # optional
        # Version of Qt to install
        #version: 5.12.7 # optional, default is 5.12.7
        # Host platform
        #host: windows # optional
        # Target platform for build
        #target: desktop # optional, default is desktop
        # Architecture for Windows/Android
        #arch: win32_mingw73 # optional
        # Whether or not to install Qt dependencies on Linux
        #install-deps: true # optional, default is true
        #modules: core gui xml network widgets printsupport

    - uses: actions/checkout@v1

    - name: Qmake and make
      working-directory: d:/a/qt-github-build/qt-github-build
      run: | 
        qmake.exe qt-github-build.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
        mingw32-make.exe qmake_all
        
    - name: Make mingw32
      working-directory: d:/a/qt-github-build/qt-github-build
      run: mingw32-make.exe -j8

