name: CI

env:
  QT_VERSION:     "5.12.7"
  MINGW_VERSION:  "win64_mingw73"
  MINGW_PATH:     "mingw73_64"

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      
    - name: Install correct version of mingw
      run: |
        choco uninstall mingw --force
        choco uninstall strawberryperl --force
        choco install mingw --version=7.3.0 

    - name: Install Qt
      uses: jurplel/install-qt-action@v2.6.2
      with:
        version: ${{ env.QT_VERSION }}
        arch: ${{ env.MINGW_VERSION }}
        extra: --external 7z

    #- name: Set path and check mingw g++ version
#      run: |
 #       echo "::add-path::d:/a/qt-github-console/Qt/5.11.3/mingw53_32/bin"
  #      refreshenv
   #     Write-Output (Get-Command g++.exe).Path
    #    g++.exe --version
      
    - uses: actions/checkout@v1

    - name: Qmake and make
      working-directory: d:/a/qt-github-build/qt-github-build
      run: | 
        qmake.exe qt-github-build.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
        mingw32-make.exe qmake_all
        
    - name: Make mingw32
      working-directory: d:/a/qt-github-build/qt-github-build
      run: mingw32-make.exe -j8

    - name: Show the build artifacts
      working-directory: d:/a/qt-github-build/qt-github-build
      run: | 
        ls
        ls releases 

