name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    
    - name: Check mingw g++ version
      run: g++.exe --version
      
    - name: Install correct version of mingw
      run: |
        choco uninstall mingw --force
        choco install mingw --version=5.3.0
        
    - name: Check mingw g++ version
      run: g++.exe --version
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v2 #@v2.5.3
      with:
        version: 5.11.3 # 5.12.7
        arch: win32_mingw53 # mingw73 much slower download
        extra: --external 7z

    - name: Qt5_DIR environment variable
      run: echo %Qt5_DIR%
      
    - uses: actions/checkout@v1

    - name: Qmake and make
      working-directory: d:/a/qt-github-build/qt-github-build
      run: | 
        qmake.exe qt-github-build.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
        mingw32-make.exe qmake_all
        
    - name: Make mingw32
      working-directory: d:/a/qt-github-build/qt-github-build
      run: mingw32-make.exe -j8

